poli-page:
  api-key: ${POLI_PAGE_API_KEY}
  base-url: ${POLI_PAGE_BASE_URL:https://api-develop.poli.page}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, conditions

spring:
  main:
    banner-mode: log

logging:
  level:
    page.poli: INFO
